import type { Customer, Inquiry, Project, Unit } from './types'

export const mockProjects: Project[] = [
  {
    _id: 'proj-1',
    name: 'Panorama Žabiny',
    slug: 'panorama-zabiny',
    location: 'Brno — Žabiny',
    type: 'apartment',
    status: 'available',
    price: '5 420 000',
    units: 24,
    year: 2026,
    featured: true,
    websiteUrl: 'https://panoramazabiny.cz',
  },
  {
    _id: 'proj-2',
    name: 'Riverline Lofts',
    slug: 'riverline-lofts',
    location: 'Brno — Štýřice',
    type: 'apartment',
    status: 'reserved',
    price: 'From €310,000',
    units: 12,
    year: 2025,
  },
  {
    _id: 'proj-3',
    name: 'Vltava House',
    slug: 'vltava-house',
    location: 'Český Krumlov',
    type: 'house',
    status: 'available',
    price: '€890,000',
    units: 1,
    year: 2025,
  },
  {
    _id: 'proj-4',
    name: 'Axis Offices',
    slug: 'axis-offices',
    location: 'Ostrava — Moravská',
    type: 'commercial',
    status: 'available',
    price: 'From €1.2M',
    units: 6,
    year: 2026,
  },
]

export const mockUnits: Unit[] = [
  {
    _id: 'unit-1',
    label: 'A1.1',
    projectName: 'Panorama Žabiny',
    status: 'available',
    floor: 1,
    rooms: 2,
    areaSqm: 68,
    priceCzk: 5420000,
  },
  {
    _id: 'unit-2',
    label: 'A2.3',
    projectName: 'Panorama Žabiny',
    status: 'reserved',
    floor: 2,
    rooms: 3,
    areaSqm: 92,
    priceCzk: 7150000,
    customerName: 'Jana Nováková',
  },
  {
    _id: 'unit-3',
    label: 'B1.2',
    projectName: 'Panorama Žabiny',
    status: 'sold',
    floor: 1,
    rooms: 2.5,
    areaSqm: 74,
    priceCzk: 5890000,
    customerName: 'Martin Svoboda',
  },
  {
    _id: 'unit-4',
    label: 'L3',
    projectName: 'Riverline Lofts',
    status: 'available',
    floor: 3,
    rooms: 2,
    areaSqm: 81,
    priceCzk: 6200000,
  },
]

export const mockCustomers: Customer[] = [
  {
    _id: 'cust-1',
    name: 'Jana Nováková',
    email: 'jana.novakova@email.cz',
    phone: '+420 777 123 456',
    status: 'reservation',
    budget: '6–8M Kč',
    preferredLanguage: 'cs',
    source: 'panoramazabiny.cz',
    interestedProjects: ['Panorama Žabiny'],
    portalAccess: true,
    notes: 'Interested in A2.3 — site visit scheduled.',
  },
  {
    _id: 'cust-2',
    name: 'Martin Svoboda',
    email: 'martin.svoboda@email.cz',
    phone: '+420 603 987 654',
    status: 'contract',
    budget: '5–6M Kč',
    preferredLanguage: 'cs',
    source: 'Referral',
    interestedProjects: ['Panorama Žabiny'],
    portalAccess: true,
  },
  {
    _id: 'cust-3',
    name: 'Emily Carter',
    email: 'emily.carter@mail.com',
    phone: '+44 7700 900123',
    status: 'qualified',
    budget: '€400–500k',
    preferredLanguage: 'en',
    source: 'ouren.cz / journal',
    interestedProjects: ['Riverline Lofts', 'Vltava House'],
    portalAccess: false,
  },
  {
    _id: 'cust-4',
    name: 'Petr Horák',
    email: 'petr.horak@firma.cz',
    phone: '+420 731 555 010',
    status: 'lead',
    budget: 'Commercial lease',
    preferredLanguage: 'cs',
    source: 'Sell with us form',
    interestedProjects: ['Axis Offices'],
    portalAccess: false,
  },
]

export const mockInquiries: Inquiry[] = [
  {
    _id: 'inq-1',
    type: 'buy',
    name: 'Emily Carter',
    email: 'emily.carter@mail.com',
    phone: '+44 7700 900123',
    message: 'Looking for a loft in Brno with parking.',
    status: 'inProgress',
    createdAt: '2026-05-20T10:00:00.000Z',
    relatedProjectName: 'Riverline Lofts',
  },
  {
    _id: 'inq-2',
    type: 'sell',
    name: 'Petr Horák',
    email: 'petr.horak@firma.cz',
    phone: '+420 731 555 010',
    propertyType: 'commercial',
    estimatedValue: '12M Kč',
    message: 'Want to list a small office building in Ostrava.',
    status: 'new',
    createdAt: '2026-05-24T14:30:00.000Z',
  },
  {
    _id: 'inq-3',
    type: 'contact',
    name: 'Klára Dvořáková',
    email: 'klara.d@email.cz',
    message: 'Requesting brochure for Panorama Žabiny.',
    status: 'done',
    createdAt: '2026-05-18T09:15:00.000Z',
    relatedProjectName: 'Panorama Žabiny',
  },
]
